name:                aoc2022
version:             0.1.0.0
github:              "1in1/Advent-of-Code-2022"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- split
- lens
- containers
- unordered-containers
- MissingH
- hashable
- extra
- pqueue
- optparse-applicative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2

library:
  source-dirs: solutions
  default-extensions: TupleSections
  ghc-options:
    - -O2

executables:
  aoc2022:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
      - aoc2022

